### ISSUE TITLE
Got Exception on Runtime

### ISSUE THREAD

**Issue by shyamkumarm** [sockeqwe/Model-View-Intent-Android#2]
java.lang.IllegalStateException: View ID 2131492948 for 'editSearch' not found.

**Comment by sockeqwe** [comment]
Have you tried to clean and rebuild the project?

Shyamkumar notifications@github.com schrieb am Mi., 1. Juni 2016, 14:58:

**Comment by shyamkumarm** [comment]
Yes But still getting same error,

06-06 12:44:55.432 7126-7126/com.hannesdorfmann.mvi W/System.err: java.lang.IllegalStateException: View ID 2131492948 for 'editSearch' not found.
06-06 12:44:55.433 7126-7126/com.hannesdorfmann.mvi W/System.err:     at butterknife.ButterKnifeKt.viewNotFound(ButterKnife.kt:78)
06-06 12:44:55.433 7126-7126/com.hannesdorfmann.mvi W/System.err:     at butterknife.ButterKnifeKt.access$viewNotFound(ButterKnife.kt:1)
06-06 12:44:55.433 7126-7126/com.hannesdorfmann.mvi W/System.err:     at butterknife.ButterKnifeKt$required$1.invoke(ButterKnife.kt:82)
06-06 12:44:55.433 7126-7126/com.hannesdorfmann.mvi W/System.err:     at butterknife.ButterKnifeKt$required$1.invoke(ButterKnife.kt)
06-06 12:44:55.433 7126-7126/com.hannesdorfmann.mvi W/System.err:     at butterknife.Lazy.getValue(ButterKnife.kt:103)
06-06 12:44:55.433 7126-7126/com.hannesdorfmann.mvi W/System.err:     at com.hannesdorfmann.mvi.SearchActivity.getEditSearch(SearchActivity.kt:0)
06-06 12:44:55.433 7126-7126/com.hannesdorfmann.mvi W/System.err:     at com.hannesdorfmann.mvi.SearchActivity.access$getEditSearch$p(SearchActivity.kt:15)
06-06 12:44:55.433 7126-7126/com.hannesdorfmann.mvi W/System.err:     at com.hannesdorfmann.mvi.SearchActivity$searchIntent$1.call(SearchActivity.kt:38)
06-06 12:44:55.433 7126-7126/com.hannesdorfmann.mvi W/System.err:     at com.hannesdorfmann.mvi.SearchActivity$searchIntent$1.call(SearchActivity.kt:15)
06-06 12:44:55.433 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
06-06 12:44:55.434 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
06-06 12:44:55.434 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Observable$2.call(Observable.java:162)
06-06 12:44:55.434 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Observable$2.call(Observable.java:154)
06-06 12:44:55.434 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8098)
06-06 12:44:55.434 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:172)
06-06 12:44:55.434 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:136)
06-06 12:44:55.434 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:79)
06-06 12:44:55.434 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowpath(OnSubscribeFromIterable.java:97)
06-06 12:44:55.434 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:73)
06-06 12:44:55.434 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:211)
06-06 12:44:55.434 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:49)
06-06 12:44:55.434 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:32)
06-06 12:44:55.434 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Observable$2.call(Observable.java:162)
06-06 12:44:55.435 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Observable$2.call(Observable.java:154)
06-06 12:44:55.435 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Observable$2.call(Observable.java:162)
06-06 12:44:55.435 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Observable$2.call(Observable.java:154)
06-06 12:44:55.435 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Observable$2.call(Observable.java:162)
06-06 12:44:55.435 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Observable$2.call(Observable.java:154)
06-06 12:44:55.435 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Observable$2.call(Observable.java:162)
06-06 12:44:55.435 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Observable$2.call(Observable.java:154)
06-06 12:44:55.435 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Observable.subscribe(Observable.java:8191)
06-06 12:44:55.435 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Observable.subscribe(Observable.java:8158)
06-06 12:44:55.435 7126-7126/com.hannesdorfmann.mvi W/System.err:     at rx.Observable.subscribe(Observable.java:7962)
06-06 12:44:55.435 7126-7126/com.hannesdorfmann.mvi W/System.err:     at com.hannesdorfmann.mvi.SearchPresenter.attachView(SearchPresenter.kt:24)
06-06 12:44:55.435 7126-7126/com.hannesdorfmann.mvi W/System.err:     at com.hannesdorfmann.mvi.SearchPresenter.attachView(SearchPresenter.kt:14)
06-06 12:44:55.435 7126-7126/com.hannesdorfmann.mvi W/System.err:     at com.hannesdorfmann.mosby.mvp.delegate.MvpInternalDelegate.attachView(MvpInternalDelegate.java:63)
06-06 12:44:55.436 7126-7126/com.hannesdorfmann.mvi W/System.err:     at com.hannesdorfmann.mosby.mvp.delegate.ActivityMvpDelegateImpl.onCreate(ActivityMvpDelegateImpl.java:67)
06-06 12:44:55.436 7126-7126/com.hannesdorfmann.mvi W/System.err:     at com.hannesdorfmann.mosby.mvp.MvpActivity.onCreate(MvpActivity.java:42)
06-06 12:44:55.436 7126-7126/com.hannesdorfmann.mvi W/System.err:     at com.hannesdorfmann.mvi.SearchActivity.onCreate(SearchActivity.kt:25)
06-06 12:44:55.436 7126-7126/com.hannesdorfmann.mvi W/System.err:     at android.app.Activity.performCreate(Activity.java:6251)
06-06 12:44:55.436 7126-7126/com.hannesdorfmann.mvi W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
06-06 12:44:55.436 7126-7126/com.hannesdorfmann.mvi W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
06-06 12:44:55.436 7126-7126/com.hannesdorfmann.mvi W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
06-06 12:44:55.436 7126-7126/com.hannesdorfmann.mvi W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
06-06 12:44:55.436 7126-7126/com.hannesdorfmann.mvi W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
06-06 12:44:55.436 7126-7126/com.hannesdorfmann.mvi W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
06-06 12:44:55.436 7126-7126/com.hannesdorfmann.mvi W/System.err:     at android.os.Looper.loop(Looper.java:148)
06-06 12:44:55.436 7126-7126/com.hannesdorfmann.mvi W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
06-06 12:44:55.436 7126-7126/com.hannesdorfmann.mvi W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-06 12:44:55.436 7126-7126/com.hannesdorfmann.mvi W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-06 12:44:55.437 7126-7126/com.hannesdorfmann.mvi W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
